addons:
  code_climate:
    repo_token: f85a97cc6f5d83bb8ae8f152858f5b074a278da6820af4c268a0cffd636ac0d4

after_success:
  - bundle exec codeclimate-test-reporter

gemfile:
  - gemfiles/activesupport_4.gemfile
  - gemfiles/activesupport_5.gemfile
  - gemfiles/latest.gemfile

language: ruby

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
